### ISSUE TITLE
App crashing After Retrieval of SMS

### ISSUE THREAD

**Issue by codeilm** [debutdeveloper/sms_retriever#18]
I am using Flutter: 2.5.1 and app is crashing after receiving SMS.

log on crash:

W/BpBinder(32619): Slow Binder: BpBinder transact took 305 ms, interface=com.google.android.gms.auth.api.phone.internal.ISmsRetrieverApiService, code=1 oneway=false
E/getSimpleName(32619): task started
D/AndroidRuntime(32619): Shutting down VM
E/AndroidRuntime(32619): FATAL EXCEPTION: main
E/AndroidRuntime(32619): Process: com.example.sms_retrieve_practice, PID: 32619
E/AndroidRuntime(32619): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.example.sms_retrieve_practice (has extras) } in com.debut.sms_retriever.SmsRetrieverPlugin$MySMSBroadcastReceiver@d9e3616
E/AndroidRuntime(32619): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
E/AndroidRuntime(32619): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime(32619): 	at android.os.Handler.handleCallback(Handler.java:914)
E/AndroidRuntime(32619): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(32619): 	at android.os.Looper.loop(Looper.java:225)
E/AndroidRuntime(32619): 	at android.app.ActivityThread.main(ActivityThread.java:7564)
E/AndroidRuntime(32619): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32619): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(32619): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(32619): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(32619): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
E/AndroidRuntime(32619): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(32619): 	at com.debut.sms_retriever.SmsRetrieverPlugin$MySMSBroadcastReceiver.onReceive(SmsRetrieverPlugin.kt:98)
E/AndroidRuntime(32619): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
E/AndroidRuntime(32619): 	... 8 more
I/flutter (32619): SMS code : Your example code is: 123456 OQHkf869GkB
D/OOMEventManagerFK(32619): checkEventAndDumpForJE: 0
I/Process (32619): Sending signal. PID: 32619 SIG: 9

**Comment by codeilm** [comment]
This is happening randomly, sometime it works and sometime it crashes.

My Flutter Doctor:
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.1348], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.2)
[√] Connected device (1 available)

• No issues found!

flutter doctor --verbose
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.1348], locale en-IN)
    • Flutter version 2.5.1 at C:\src\flutter251
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (8 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\admin\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\admin\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\admin\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.2)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (1 available)
    • Redmi Note 8 (mobile) • 1488613f • android-arm64 • Android 10 (API 29)

• No issues found!
